apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "dify-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager